package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostPatientHandlerFunc turns a function with the right signature into a post patient handler
type PostPatientHandlerFunc func(PostPatientParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostPatientHandlerFunc) Handle(params PostPatientParams) middleware.Responder {
	return fn(params)
}

// PostPatientHandler interface for that can handle valid post patient params
type PostPatientHandler interface {
	Handle(PostPatientParams) middleware.Responder
}

// NewPostPatient creates a new http.Handler for the post patient operation
func NewPostPatient(ctx *middleware.Context, handler PostPatientHandler) *PostPatient {
	return &PostPatient{Context: ctx, Handler: handler}
}

/*PostPatient swagger:route POST /patient postPatient

PostPatient post patient API

*/
type PostPatient struct {
	Context *middleware.Context
	Handler PostPatientHandler
}

func (o *PostPatient) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostPatientParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
