package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Med Tracker for keeping dosages straight when caring for your wife :)",
    "title": "med-tracker",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/patient": {
      "get": {
        "responses": {
          "200": {
            "description": "list patients",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/patient"
              }
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/patient"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "create cert",
            "schema": {
              "$ref": "#/definitions/patient"
            }
          },
          "default": {
            "description": "generic error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "med": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "x-go-custom-tag": "db:\"id\"",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 1,
          "x-go-custom-tag": "db:\"name\""
        }
      }
    },
    "patient": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "x-go-custom-tag": "db:\"id\"",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 1,
          "x-go-custom-tag": "db:\"name\""
        }
      }
    },
    "plan": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "x-go-custom-tag": "db:\"id\""
        }
      }
    }
  }
}`))
}
